@Surl.API_HostAddress = http://localhost:5148

GET {{Surl.API_HostAddress}}/shorts
Accept: application/json

###

GET {{Surl.API_HostAddress}}/r/C8g7y0
Accept: application/json

###
POST {{Surl.API_HostAddress}}/shorten
Content-Type: application/json
{
  "url": "https://www.google.com"
}

###

DELETE {{Surl.API_HostAddress}}/shorten/nqjpiW
Content-Type: application/json
###

DELETE {{Surl.API_HostAddress}}/flush
Content-Type: application/json