// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Surl.API.Data;

#nullable disable

namespace Surl.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250627013933_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Surl.API.Model.UrlShorten", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClickCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortenedUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UrlShorten");
                });

            modelBuilder.Entity("Surl.API.Model.UrlShortenAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UrlShortenId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UrlShortenId");

                    b.ToTable("UrlShortenAccess");
                });

            modelBuilder.Entity("Surl.API.Model.UrlShortenAccess", b =>
                {
                    b.HasOne("Surl.API.Model.UrlShorten", "UrlShorten")
                        .WithMany("UrlShortenAccesses")
                        .HasForeignKey("UrlShortenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UrlShorten");
                });

            modelBuilder.Entity("Surl.API.Model.UrlShorten", b =>
                {
                    b.Navigation("UrlShortenAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
